export default{
    CHANGE_TEMPERATURE_TYPE:'CHANGE_TEMPERATURE_TYPE',
    SET_CURRENT_CITY:'SET_CURRENT_CITY',
    REMOVE_FROM_FAVORITES:'REMOVE_FROM_FAVORITES',
    ADD_TO_FAVORITES:'ADD_TO_FAVORITES',
    SET_ERROR_MODAL:'SET_ERROR_MODAL',
    CLOSE_ERROR_MODAL:'CLOSE_ERROR_MODAL',
}